language: go

go:
    - tip

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/lestrrat/go-tcptest

script:
    - $HOME/gopath/bin/goveralls -service=travis-ci

install:
    - go get -d -v ./...
    - go build -v ./...
